version: '3.8'

name: booking-app
services:
  mysqldb:
    container_name: database
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/alternatives/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - app
  
  backend: 
    container_name: api
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    networks:
      - app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-ID=${GOOGLE_CLIENT_ID}
      - SPRING_EMAIL_USERNAME=${SPRING_EMAIL_USERNAME}
      - SPRING_EMAIL_PASSWORD=${SPRING_EMAIL_PASSWORD}
  
  frontend: 
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - app
networks:
  app:

volumes:
  db_data: {}
