version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/alternatives/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookingapp
    ports:
      - 3306:3306
    expose:
      - 3306
volumes:
  db_data: { }
